version: "2"

services:
  todo_app:
    build:
      context: .
      target: development
    ports:
      - 5000:80
    volumes:
      - type: bind
        source: todo_app
        target: /app/todo_app/todo_app
    env_file:
      - .env
